### PR TITLE
add installation instructions for Arch Linux

### PR DESCRIPTION
**Pull request by Titaniumtown**
Does what the title says.

### CODE REVIEW

**Comment by uunicorn** [comment]
Thanks for the PR,
Do you know if these instructions will still work if `fprintd` and/or `libfprint` are already installed?

**Comment by Titaniumtown** [comment]
Yes, I believe so.

**Comment by uunicorn** [comment]
The reason I'm asking is because `open-fprintd` (which `python-validity` depends on) owns the same DBus name and cannot run together with `fprintd`. Similarly `libfprint` (if used) acquires the same USB interface and will conflict with `python-validity` itself. 

Ubuntu packages which I maintain enforce this constraint, however I do not maintain Arch packages nor I have Arch environment to test if it works, so I have to trust that it works.

**Comment by Titaniumtown** [comment]
It does conflict. I just tested. So that's good!

**Comment by uunicorn** [comment]
Thanks!

**Pull request merged**
